C2PQUESTIONS_TABLE_NAME = 'C2PQandA'
QUESTIONS_TABLE_KEY_NAME = 'id'

QUESTIONS_TABLE_NAME = 'trivia'


CA2QUESTIONS_TABLE_NAME = 'CA2QandA'
CA220QUESTIONS_TABLE_NAME = 'CA220QandA'
C2PQUESTIONS_TABLE_NAME = 'C2PQandA'
CDAQUESTIONS_TABLE_NAME = 'CDAQandA'
CMLQUESTIONS_TABLE_NAME = 'CMLQandA'
CDANQUESTIONS_TABLE_NAME = 'CDANQandA'



POOL_ARN = (
    'arn:aws:cognito-idp:us-east-2:001178231653:userpool/us-east-2_HqMyKkokN')

IDENTITY_POOL_ID = (
    'us-east-2:0eca9f1c-4400-4e4a-ad2c-f7e3a36f44f8'
)
